try {
  variable.name = "Adam"; 
  console.log("Estamos probando un try");
} catch(error) {
  const myError = {
    code: 434,
    message: "Programe bien",
  };
  console.log(myError);
}
